export const DATE_FORMATS = {
  DAY_MONTH_YEAR_HOURS_MINUTES: 'ddd, DD MMM, HH:mm',
  NATIVE_DATEPICKER_INPUT_DATE: 'DD MMMM YYYY, h:mm',
  NATIVE_DATEPICKER_DATE: 'YYYY-MM-DDTHH:mm',
  DAY_MONTH_YEAR: 'Do MMM YY',
  HOURS_MINUTES: 'H:mm',
  MONTH_DAY: 'MMM DD',
  HOURS: 'HH',
  DAYS: 'DD',
}
